### ISSUE TITLE
Roadmap / Contributing

### ISSUE THREAD

**Issue by mschauer** [mschauer/CausalInference.jl#1]
Contributions, comments and feature requests are most welcome.

The vanilla PC algorithm, the Markov skeleton algorithm and a function to check `d`-separation for directed graphs are implemented.

Regards!

Tagging @tfgit, @jeffwong

**Comment by mschauer** [comment]
There is unfinished work on independence tests for categorical variables in #11, if you happen to need that, please ping us.

**Comment by schnirz** [comment]
The CMI tests take quite a long time right now, even for moderately sized data sets. It would be really interesting to investigate different approaches to speeding these tests up, e.g. via parallelization of the CMI tests or of the PC/FCI algorithms.

**Comment by mschauer** [comment]
Can be reopen if useful.
