### ISSUE TITLE
Data for example unavailable

### ISSUE THREAD

**Issue by jademackay** [mschauer/CausalInference.jl#12]
The NCI-60 data (http://nugget.unisa.edu.au/ParallelPC/data/real/NCI-60.csv) specified in the documentation example (https://mschauer.github.io/CausalInference.jl/latest/#Example-1) is no longer available.

**Comment by mschauer** [comment]
Thank you. The entire "nugget" server seems to be down. Maybe this is temporal, in any case for the meantime: https://www.dropbox.com/s/vr78pqd0aeccu9o/nci60.csv?dl=0

**Comment by jademackay** [comment]
That's great, thanks :-)

**Comment by mschauer** [comment]
It is back up!

**Comment by undefdev** [comment]
It's not available again.

**Comment by mschauer** [comment]
I think we have changed the real data example to use https://www.ccd.pitt.edu//wp-content/uploads/files/Retention.txt which is also still available.  Which file exactly are you running?

**Comment by undefdev** [comment]
Ah, my bad! I guess Google made me land on the wrong docs. Somehow I ended up here https://docs.juliahub.com/CausalInference/aEe3Z/0.5.5/
Sorry for the false alert.

**Comment by mschauer** [comment]
Ok 👍
