### ISSUE TITLE
Retrieve Equations from CausalGraph

### ISSUE THREAD

**Issue by JorgeLuizFranco** [mschauer/CausalInference.jl#154]
The ideia is after obtaining a Causal DAG retrieve the causal equations as in an SCM/SEM.

**Comment by JorgeLuizFranco** [comment]
@mschauer in the context of the project should I create a new .jl named `equations.jl` or insert into another existing .jl? Since there is a file for each algorithm, I don't think it makes sense to insert the function I am creating in every file, since, for now, it is going to be the same.

**Comment by mschauer** [comment]
yeah you are right
