### ISSUE TITLE
changes to documentation code

### ISSUE THREAD

**Issue by currymj** [mschauer/CausalInference.jl#6]
This is a small thing, but it may avoid some confusion as people try to get the example code working.

On 1.0.1 (and maybe earlier), one needs `using DelimitedFiles` in order to use `readdlm`.

**Comment by currymj** [comment]
Likewise one needs `using LinearAlgebra` and `using Statistics`; and the call to `cor` now needs a keyword `dims` for its second argument.

**Comment by mschauer** [comment]
Thanks, fixed it.
