### ISSUE TITLE
Implement sufficient adjustment criterion extending the backdoor criterion

### ISSUE THREAD

**Issue by mschauer** [mschauer/CausalInference.jl#60]
For DAGs: https://arxiv.org/pdf/1203.3515.pdf
More general for CPDAG/MAG/PAG: https://auai.org/uai2015/proceedings/papers/155.pdf

**Comment by mschauer** [comment]
Is this for DAGs somehow included in #82 , @mwien?

**Comment by mwien** [comment]
Yes, ```find_covariate_adjustment``` finds a set $Z$ (with additional constraints $I$ and $R$, i.e. $I \subseteq Z \subseteq R$) which satisfies the adjustment criterion given in the Shpitser et al. paper (Def. 5) if such a set exists: https://github.com/mwien/CausalInference.jl/blob/ab5f4c9044045ebeaeeb5b4558d5cefc9dbe8b63/src/gensearch.jl#L159C1-L167

Similarly, ```find_min_covariate_adjustment``` and ```list_covariate_adjustment``` finds an inclusion minimal set satisfying this criterion resp. lists all such sets.

This is in contrast to function ```find_backdoor_adjustment```, which find sets which satisfy the classical backdoor criterion by Pearl.

**Comment by mschauer** [comment]
Closed by #82
