### ISSUE TITLE
Implement search for adjustment sets

### ISSUE THREAD

**Issue by mschauer** [mschauer/CausalInference.jl#61]
High effort PR, but rewarding and a straight solution:

The problem is as follows: There are two variables X and Y and we want to know the effect of X on Y. Which variables do we need as control variables to get an unbiased estimate? 

This assumes that you are a bit familiar with causal inference in particular with measuring 
causal effect and representing causal structure with a DAG*

But the task is simpler than that.

The package already has the backdoor criterion implemented to check if something is an adjustment set. To find one we will employ brute force: check every set if it is an adjustment set until done.

**Comment by mschauer** [comment]
Some resources: 
 
 * The very nice introduction to DAGs of the ggdag R package: https://ggdag.malco.io/articles/intro-to-dags.html
I made a issue to actually translate that #62 

 * The very long (3h) and very good video lecture https://www.youtube.com/watch?v=KNPYUVmY3NM
 
* The technical but good chapter on DAGs in Wassermans "Statistical Machine Learning" course http://www.stat.cmu.edu/~larry/=sml/ and the next chapter on causality

**Comment by mwien** [comment]
Currently working on this and related stuff here: https://github.com/mwien/CausalInference.jl/blob/idalgorithms/src/gensearch.jl

Gonna submit a PR soon.

**Comment by mschauer** [comment]
Nice! Feel free to submit work in progress as PR too
