### ISSUE TITLE
[FR] TikzGraphs as conditional dependency + text-based output method

### ISSUE THREAD

**Issue by svilupp** [mschauer/CausalInference.jl#73]
Thank you for the great package!

Unfortunately, TikzGraphs dependency makes it impossible to add for users with M1 Macs. It's linked to Tectonic binaries (see [link](https://github.com/MichaelHatherly/Tectonic.jl/issues/13)), which get pulled in with TikzGraphs->TikzPictures->Tectonic.

I'd be happy to open a PR to add a fallback text-based output and load plotting with TikzGraphs via Requires.

Otherwise, I've tested the functionality (by dev'ing and removing manually the Tikz dependencies) and all seems to work as expected.

**Comment by mschauer** [comment]
Please make a PR, that would be great!

**Comment by svilupp** [comment]
Sorry for being so slow!

Two questions that will help me focus energy:
- Should I write the conditional deps in the new "package extensions" style that is backwards compatible? (PGFXPlotx example) Or rather stick to Requires.jl?
- I have not found a simple generic way to display a graph via text without too much effort. I'm considering just sorting them printing a bit and then printing the edge in a tabular format (ala TabularDisplay) - It's better than nothing having an output at all. Would that be sensible?

**Comment by mschauer** [comment]
Let's go by "Perfect is the enemy of good"? Tabular display would be helpful and only do the new style if it doesn't stall you. I am happy anyway if you and me are able to fix the problem.

**Comment by mschauer** [comment]
Closed by #74
